# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevtest',
                'doc_host': 'https://ianxek.github.io',
                'git_url': 'https://github.com/ianxek/nbdevtest',
                'lib_path': 'nbdevtest'},
  'syms': {'nbdevtest.core': {'nbdevtest.core.foo': ('core.html#foo', 'nbdevtest/core.py')}}}
